duanquanlynhanvien/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #andmoreurl qcustom
    path('quydeptrai/', admin.site.urls),

    path('', include('nhanvien.urls')),

    path('', include('polls.urls')),


]

nhanvien/urls.py
from django.contrib import admin
from django.urls import path
from nhanvien import views

app_name = 'nhanvien'
urlpatterns = [
    path('',views.show),
    path('addnv', views.addnv),
    path('show',views.show),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.destroy),
]

polls/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'polls'

urlpatterns = [
    path('detail/<int:question_id>/', views.detailView, name="detail"),
    #dieu huong tuie  ket cua menu
    path('viewvotelist/', views.viewlist, name='viewvotelist'),

    #path('', views.viewlist, name='view_list'),

    path('polls/', views.viewlist, name='view_list'),

    path('votedetail/<int:question_id>', views.vote, name='vote'),
    #path('<int:question_id>', views.vote, name='vote'),
]

nhanvien/models.py
from django.db import models

class Nhanvien(models.Model):
    nvid = models.CharField(max_length=20)
    nvname = models.CharField(max_length=100)
    nvemail = models.EmailField()
    nvcontact = models.CharField(max_length=300)
    class Meta:
        db_table = "nhanvien"

    def __str__(self):
        return self.nvid

polls/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    time_pub = models.DateTimeField()
    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=100)
    vote = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

nhanvien/forms.py
from django import forms
from nhanvien.models import Nhanvien
class NhanvienForm(forms.ModelForm):
    class Meta:
        model = Nhanvien
        fields = "__all__"

nhanvien/views.py
from django.shortcuts import render, redirect
from nhanvien.forms import NhanvienForm
from nhanvien.models import Nhanvien

# Create your views here.
def addnv(request):
    #nếu có gửi POST thì chạy
    if request.method == "POST":
        form = NhanvienForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/show')
            except:
                pass
    else:
        form = NhanvienForm()
    #Load giao diện
    return render(request,'index.html',{'form':form})
def show(request):
    tatcanhanvien = Nhanvien.objects.all()
    return render(request,"show.html",{'tatcanhanvien':tatcanhanvien})
def edit(request, id):
    nhanvien = Nhanvien.objects.get(id=id)
    return render(request,'edit.html', {'nhanvien':nhanvien})
def update(request, id):
    nhanvien = Nhanvien.objects.get(id=id)
    form = NhanvienForm(request.POST, instance=nhanvien)
    if form.is_valid():
        form.save()
        return redirect("/show")
    return render(request, 'edit.html', {'nhanvien': nhanvien})
def destroy(request, id):
    nhanvien = Nhanvien.objects.get(id=id)
    nhanvien.delete()
    return redirect("/show")

polls/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render
from .models import Question
# Create your views here.



def viewlist(request):
    #get_object_or_404(Question, pk=1) Question.objects.all()
    list_question = Question.objects.all()
    context = {"dsquest": list_question}
    return render(request, "polls/question_list.html", context)


def detailView(request, question_id):
    q = Question.objects.get(pk=question_id)
    return render(request, "polls/detail_question.html", {"qs": q})

def vote(request, question_id):
    q = Question.objects.get(pk=question_id)
    try:
        dulieu = request.POST["choice"]
        c = q.choice_set.get(pk=dulieu)

    except:
        HttpResponse("loi khong co choice nay dau")
    c.vote = c.vote + 1
    c.save()
    return render(request, "polls/result.html", {"q":q})

nhanvien/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Show Nhân Viên</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
     {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<body>

    <div class="container">
        <div class="row my-3">
        <nav class="navbar navbar-darkx bg-primary navbar-expand-lgx navbar-light bg-light">
          <a class="navbar-brand" href="../"> Navbar </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
              <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
              </li>
                <li class="nav-item">
                <a class="nav-link" href="../addnv">Add new</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
              </li>
                 <li class="nav-item">
                <a class="nav-link" href="../polls">polls-app</a>
              </li>
                <li class="nav-item">
                <a class="nav-link" href="../quydeptrai">Admin</a>
              </li>
            </ul>
          </div>
        </nav>
        </div>
    </div>

    <div class="container content">
        {% block content %}
        {% endblock %}
    </div>

    <footer class="text-muted py-5">
      <div class="container">
        <p class="float-end mb-1">
          <a href="#">Back to top</a>
        </p>
        <p class="mb-1">Quanlynhanvien project as Nhanvien app example is &copy; MQD</p>
      </div>
    </footer>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
</body>
</html>

nhanvien/templates/edit.html
{% extends 'base.html' %}

{% block content %}
        <div class="row">
        <form method="POST" class="post-form" action="/update/{{nhanvien.id}}">
                {% csrf_token %}
            <div class="containerX">
        <br>
            <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-4">
            <h3>Cập Nhật Thông Tin Nhân Viên</h3>
            </div>
          </div>
            <div class="form-group row">
            <label class="col-sm-2 col-form-label">Mã Nhân Viên:</label>
            <div class="col-sm-4">
                <input type="text" name="nvid" id="id_nvid" required maxlength="20" value="{{ nhanvien.nvid }}"/>
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-2 col-form-label">Tên Nhân Viên:</label>
            <div class="col-sm-4">
                <input type="text" name="nvname" id="id_nvname" required maxlength="100" value="{{ nhanvien.nvname }}" />
            </div>
          </div>
            <div class="form-group row">
            <label class="col-sm-2 col-form-label">Email Nhân Vien:</label>
            <div class="col-sm-4">
                <input type="email" name="nvemail" id="id_nvemail" required maxlength="254" value="{{ nhanvien.nvemail }}" />
            </div>
          </div>
            <div class="form-group row">
            <label class="col-sm-2 col-form-label">Liên Hệ Nhân Viên:</label>
            <div class="col-sm-4">
                <input type="text" name="nvcontact" id="id_nvcontact" required maxlength="15" value="{{ nhanvien.nvcontact }}" />
            </div>
          </div>
            <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-4">
            <button type="submit" class="btn btn-success">Cập nhật</button>
            </div>
          </div>
            </div>
        </form>
        </div>
{% endblock %}

nhanvien/templates/index.html
{% extends 'base.html' %}

{% block content %}

        <div class="row">
        <form method="POST" class="post-form" action="/addnv">
                {% csrf_token %}
            <div class="containerx">

            <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-4">
            <h3>Thêm nhân viên</h3>
            </div>
          </div>
            <div class="form-group row">
            <label class="col-sm-2 col-form-label">Mã Nhân Viên:</label>
            <div class="col-sm-4">
              {{ form.nvid }}
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-2 col-form-label">Tên Nhân Viên:</label>
            <div class="col-sm-4">
              {{ form.nvname }}
            </div>
          </div>
            <div class="form-group row">
            <label class="col-sm-2 col-form-label">Email Nhân Viên:</label>
            <div class="col-sm-4">
              {{ form.nvemail }}
            </div>
          </div>
            <div class="form-group row">
            <label class="col-sm-2 col-form-label">Contact Nhân viên:</label>
            <div class="col-sm-4">
              {{ form.nvcontact }}
            </div>
          </div>
            <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-4">
            <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          </div>
            </div>
        </form>
        </div>

{% endblock content %}

nhanvien/templates/show.html
{% extends 'base.html' %}

{% block content %}

    <div class="row table-responsive">
        <table class="table table-striped table-bordered table-sm">
            <thead class="thead-dark">
            <tr>
                <th scope="col">Mã Nhân Viên:</th>
                <th scope="col">Tên Nhân Viên</th>
                <th scope="col">Email Nhân Viên</th>
                <th scope="col">Contact Nhân Viên</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
        {% for nhanvien in tatcanhanvien %}
            <tr>
                <td scope="row">{{ nhanvien.nvid }}</td>
                <td>{{ nhanvien.nvname }}</td>
                <td>{{ nhanvien.nvemail }}</td>
                <td>{{ nhanvien.nvcontact }}</td>
                <td>
                    <a href="/edit/{{ nhanvien.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>
                    <a href="/delete/{{ nhanvien.id }}">Delete</a>
                </td>
            </tr>
        {% endfor %}
            </tbody>
        </table>
    </div>

        <div class="row pagination">
            <center><a href="/addnv" class="btn btn-primary">Add New Record</a></center>

        </div>


{% endblock %}

polls/templates/polls/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{% static 'polls/style.css' %}">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
</head>

<body>

    <div class="header container">
        <h1>My website</h1>

    </div>


    <div class="content  container">

        {% block content123 %}
        {% endblock %}
    </div>



    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
</body>
</html>

polls/templates/polls/detail_question.html
{% extends 'polls/base.html' %}

{% block content123 %}
    {% if  qs %}
    <h2>Detail page: chọn câu trả lời</h2>
    <br>
<h3>{{ qs.question_text }}</h3>
        <form action="{% url 'polls:vote' qs.id %}" method="POST">
            {% csrf_token %}

        {% for item in qs.choice_set.all %}
        <div class="form-check">
            <input class="form-check-input" type="radio" name="choice" value="{{ item.id }}" id="{{ item.id }}">

            <label class="form-check-label" for="{{ item.id }}">
    {{ item.choice_text }}   (choiceid_{{ item.id }})
  </label>
            </div>
        {% endfor %}
            <br>
            <input type="submit" value="Gửi" class="btn btn-primary">

        </form>

    {% endif %}

{% endblock %}

polls/templates/polls/question_list.html
{% extends 'polls/base.html' %}

{% block content123 %}
<div class="menu container">
        <ul>
            <li><a href="../">home this project (static link)</a>
            <li><a href="{% url 'polls:viewvotelist' %}">home app (static link)</a>

            <li><a href="../admin">admin project (static link)</a></li>

<li><a href="../polls">polls (static link)</a></li>

<li><a href="../quydeptrai">admin (custom static link)</a></li>


    </div>

    <h1> Danh  sách câu hỏi</h1>
    {% if dsquest %}

<ul>

        {% for item in dsquest %}
<li><a href="{% url 'polls:detail' item.id %}">{{ item.question_text }}</a> (id_{{ item.id }})</li>

        {% endfor %}

</ul>
{% else %}
<h3 style="color:red;">Không có dữ liệu trong câu hỏi nào!!! </h3>
    {% endif %}
<div class="docs container">
    text syntax:<br>

</div>

<div class="content infopage container">
</br>
       Tài khoản đăng nhập</br>
       test - test1234

    </div>

{% endblock %}

polls/templates/polls/result.html
{% extends 'polls/base.html' %}

{% block content123 %}
    {% if q %}
        <h1>{{ q.question_text}}</h1>
<p>kết quả của cuộc bình chọn là:</p>

        {% for item in q.choice_set.all %}
<p>{{ item.choice_text }} : <span style="color:red;">{{ item.vote }}</span></p>
        {% endfor %}

<a href="{% url 'polls:view_list' %}">Vote tiếp</a>
    {% endif %}

{% endblock %}